# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy all project files to the container
COPY . .

# Expose the port on which your app runs
EXPOSE 3031

# Define the command to run your application
CMD ["node", "server.js"]
